//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DESCUENTOS_ASOCIADOS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DESCUENTOS_ASOCIADOSEntities : DbContext
    {
        public DESCUENTOS_ASOCIADOSEntities()
            : base("name=DESCUENTOS_ASOCIADOSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_ASOCIADO> TBL_ASOCIADO { get; set; }
        public virtual DbSet<TBL_CONCEPTOS> TBL_CONCEPTOS { get; set; }
        public virtual DbSet<TBL_EQUIVALENCIAS> TBL_EQUIVALENCIAS { get; set; }
        public virtual DbSet<TBL_CONCEPTO_ASOCIADO> TBL_CONCEPTO_ASOCIADO { get; set; }
    }
}
