//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DESCUENTOS_ASOCIADOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CONCEPTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_CONCEPTOS()
        {
            this.TBL_ASOCIADO = new HashSet<TBL_ASOCIADO>();
            this.TBL_EQUIVALENCIAS = new HashSet<TBL_EQUIVALENCIAS>();
            this.TBL_CONCEPTO_ASOCIADO = new HashSet<TBL_CONCEPTO_ASOCIADO>();
        }
    
        public decimal ID_CONCEPTO { get; set; }
        public string CODIGO_CONCEPTO { get; set; }
        public string DESCRIPCION { get; set; }
        public string ABREVIATURA { get; set; }
        public string NATURALEZA { get; set; }
        public string MODO { get; set; }
        public string TIPO_CUOTA { get; set; }
        public string APLICACION_CUOTA { get; set; }
        public string CONCEPTO_TOPE { get; set; }
        public string PERIODICIDAD_CUOTA { get; set; }
        public Nullable<double> PORCENTAJE_CUOTA { get; set; }
        public string AGRUP_CONCEPTOS { get; set; }
        public byte[] PROP_TIEMPO { get; set; }
        public string AGRUP_CALC_TIEMPO { get; set; }
        public Nullable<decimal> VAL_EXCLUD { get; set; }
        public Nullable<decimal> VALOR { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO_DESC { get; set; }
        public Nullable<System.DateTime> FECHA_FIN_DESC { get; set; }
        public byte[] ESTADO_DESC { get; set; }
        public Nullable<decimal> FORMA_PAGO { get; set; }
        public byte[] ESTADO_CONCEPTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_ASOCIADO> TBL_ASOCIADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_EQUIVALENCIAS> TBL_EQUIVALENCIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_CONCEPTO_ASOCIADO> TBL_CONCEPTO_ASOCIADO { get; set; }
    }
}
