//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DESCUENTOS_ASOCIADOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ASOCIADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_ASOCIADO()
        {
            this.TBL_CONCEPTO_ASOCIADO = new HashSet<TBL_CONCEPTO_ASOCIADO>();
        }
    
        public decimal ID_ASOCIADO { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<decimal> TELOFONO { get; set; }
        public Nullable<decimal> ID_CONCEPTO { get; set; }
        public string IDENTIFICACION { get; set; }
        public string ESTADO_ASOCIADO { get; set; }
    
        public virtual TBL_CONCEPTOS TBL_CONCEPTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_CONCEPTO_ASOCIADO> TBL_CONCEPTO_ASOCIADO { get; set; }
    }
}
