//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DESCUENTOS_ASOCIADOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CONCEPTO_ASOCIADO
    {
        public decimal ID_CONASC { get; set; }
        public Nullable<decimal> ID_CONCEPTO { get; set; }
        public Nullable<decimal> ID_ASOCIADO { get; set; }
        public Nullable<System.DateTime> FECHA_INICIAL { get; set; }
        public Nullable<System.DateTime> FECHA_FINAL { get; set; }
        public Nullable<bool> ESTADO_CUENTA { get; set; }
        public Nullable<decimal> VALOR { get; set; }
        public string PERIODICIDAD { get; set; }
        public string FORMA_PAGO { get; set; }
        public Nullable<System.DateTime> FECHA_VENC { get; set; }
    
        public virtual TBL_ASOCIADO TBL_ASOCIADO { get; set; }
        public virtual TBL_CONCEPTOS TBL_CONCEPTOS { get; set; }
    }
}
