//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DESCUENTOS_ASOCIADOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EQUIVALENCIAS
    {
        public decimal ID_EQUIVALENCIAS { get; set; }
        public string CODIGO_CONTABLE { get; set; }
        public Nullable<decimal> ID_CONCEPTO { get; set; }
        public string TOTAL { get; set; }
    
        public virtual TBL_CONCEPTOS TBL_CONCEPTOS { get; set; }
    }
}
